### ISSUE TITLE
Let's make this repo public!

### ISSUE THREAD

**Issue by jlsan92** [strvcom/terraform-aws-strv-fargate#5]
It's worth to make this public! I think that the support of the Terraform Registry is amazing in terms of how it handles the releases and the semantic version support. But in order to use it, we also need to rename this repo and follow their [convention](https://www.terraform.io/docs/registry/modules/publish.html).

I suggest the simple name of `terraform-aws-fargate-strv`

**Comment by robertrossmann** [comment]
Go for it! 👍💪
